version: "3.8"
services:
        fastapi_server:
                build: ./src
                ports:
                        - "80:8000"
        mysql_db:
                image: mysql
                ports:
                        - "3306:3306"
                expose:
                        - "3306"
                environment:
                        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                volumes:
                        - db_data:/var/lib/mysql


volumes:
        db_data:



